name: drip_logger
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_slidable: ^4.0.3
  file_saver: ^0.3.1
  shared_preferences: ^2.5.4
  flutter_riverpod: ^2.5.1
  sembast: ^3.8.6
  sembast_web: ^2.4.4
  state_notifier: ^1.0.0
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
